# Generated by Django 5.2.6 on 2025-09-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='migrationlog',
            old_name='start_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='databaseconnection',
            name='database',
        ),
        migrations.RemoveField(
            model_name='migrationlog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='migrationlog',
            name='status',
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='available_databases',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='selected_database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='migrationlog',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='migrationlog',
            name='level',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico'), ('success', 'Éxito'), ('debug', 'Depuración')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='migrationlog',
            name='message',
            field=models.TextField(default='Migración histórica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='migrationlog',
            name='stage',
            field=models.CharField(choices=[('connection', 'Conexión'), ('database_list', 'Listar bases de datos'), ('database_select', 'Selección de base de datos'), ('table_list', 'Listar tablas'), ('table_select', 'Selección de tablas'), ('column_list', 'Listar columnas'), ('column_select', 'Selección de columnas'), ('validation', 'Validación'), ('data_extraction', 'Extracción de datos'), ('data_transformation', 'Transformación de datos'), ('data_loading', 'Carga de datos'), ('rollback', 'Rollback'), ('completion', 'Finalización')], default='migracion', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='migrationlog',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='migrationprocess',
            name='allow_rollback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='migrationprocess',
            name='last_checkpoint',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationprocess',
            name='selected_database',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='migrationprocess',
            name='target_db_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_processes', to='automatizacion.databaseconnection'),
        ),
        migrations.AlterField(
            model_name='migrationprocess',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('db_selected', 'Base de datos seleccionada'), ('tables_selected', 'Tablas seleccionadas'), ('columns_selected', 'Columnas seleccionadas'), ('configured', 'Configurado'), ('validated', 'Validado'), ('ready', 'Listo para ejecutar'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='draft', max_length=20),
        ),
    ]
