# Generated by Django 4.2.23 on 2025-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0002_rename_start_time_migrationlog_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('ProcesoID', models.CharField(blank=True, max_length=36, null=True)),
                ('NombreProceso', models.CharField(blank=True, max_length=255, null=True)),
                ('FechaEjecucion', models.DateTimeField()),
                ('Estado', models.CharField(max_length=20)),
                ('ParametrosEntrada', models.TextField(blank=True, null=True)),
                ('DuracionSegundos', models.IntegerField(blank=True, null=True)),
                ('MensajeError', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Proceso',
                'verbose_name_plural': 'Logs de Procesos',
                'db_table': 'ProcesoLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadosProcesados',
            fields=[
                ('ResultadoID', models.AutoField(primary_key=True, serialize=False)),
                ('ProcesoID', models.CharField(help_text='UUID del proceso que generó este resultado', max_length=36)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, help_text='Timestamp automático de creación')),
                ('DatosProcesados', models.TextField(help_text='Datos procesados en formato JSON')),
                ('UsuarioResponsable', models.CharField(help_text='Usuario que ejecutó el proceso', max_length=100)),
                ('EstadoProceso', models.CharField(default='COMPLETADO', help_text='Estado del proceso', max_length=50)),
                ('TipoOperacion', models.CharField(blank=True, help_text='Tipo de operación realizada', max_length=100, null=True)),
                ('RegistrosAfectados', models.IntegerField(default=0, help_text='Número de registros procesados')),
                ('TiempoEjecucion', models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo de ejecución en segundos', max_digits=10, null=True)),
                ('MetadatosProceso', models.TextField(blank=True, help_text='Metadatos adicionales del proceso', null=True)),
            ],
            options={
                'verbose_name': 'Resultado Procesado',
                'verbose_name_plural': 'Resultados Procesados',
                'db_table': 'ResultadosProcesados',
                'ordering': ['-FechaRegistro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosDestino',
            fields=[
                ('UsuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=255)),
                ('NombreCompleto', models.CharField(max_length=200)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
                ('UltimoAcceso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario Destino',
                'verbose_name_plural': 'Usuarios Destino',
                'db_table': 'dbo.Usuarios',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='migrationprocess',
            name='target_table',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
