# Generated by Django 4.2.23 on 2025-10-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0003_procesolog_resultadosprocesados_usuariosdestino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
