# Generated by Django 4.2.23 on 2025-10-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0004_alter_databaseconnection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationprocess',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
