# Generated by Django 4.2.23 on 2025-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0005_alter_migrationprocess_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationprocess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='migrationprocess',
            name='target_db_name',
            field=models.CharField(default='DestinoAutomatizacion', max_length=100),
        ),
    ]
