# Generated by Django 4.2.23 on 2025-10-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0006_migrationprocess_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationprocess',
            name='column_mappings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
