# Generated by Django 4.2.23 on 2025-10-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0007_migrationprocess_column_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesosGuardados',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre_proceso', models.CharField(db_column='NombreProceso', help_text='Nombre único del proceso (sin caracteres especiales)', max_length=255)),
                ('tipo_fuente', models.CharField(db_column='TipoFuente', help_text="Tipo de fuente: 'Excel' o 'SQL'", max_length=50)),
                ('fuente', models.CharField(blank=True, db_column='Fuente', help_text='Ruta del archivo Excel o nombre de la conexión SQL', max_length=255, null=True)),
                ('hoja_tabla', models.CharField(blank=True, db_column='HojaTabla', help_text='Nombre de la hoja (Excel) o tabla (SQL) procesada', max_length=255, null=True)),
                ('destino', models.CharField(blank=True, db_column='Destino', help_text='Base o tabla destino en DestinoAutomatizacion', max_length=255, null=True)),
                ('estado', models.CharField(db_column='Estado', default='Activo', help_text='Estado lógico del proceso: Activo, Inactivo, Eliminado, etc.', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', help_text='Timestamp de creación del proceso')),
                ('fecha_actualizacion', models.DateTimeField(blank=True, db_column='FechaActualizacion', help_text='Timestamp de última modificación del proceso', null=True)),
                ('usuario_creador', models.CharField(blank=True, db_column='UsuarioCreador', help_text='Usuario que creó el proceso', max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', help_text='Descripción detallada del proceso', null=True)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, db_column='UltimaEjecucion', help_text='Timestamp de la última vez que se ejecutó el proceso', null=True)),
                ('version', models.IntegerField(db_column='Version', default=1, help_text='Versión del proceso (incrementa con cada cambio significativo)')),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', help_text='Notas adicionales, cambios realizados, etc.', null=True)),
            ],
            options={
                'verbose_name': 'Proceso Guardado (SQL Server)',
                'verbose_name_plural': 'Procesos Guardados (SQL Server)',
                'db_table': 'dbo.ProcesosGuardados',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='migrationprocess',
            name='type_configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='migrationprocess',
            name='types_inferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
