# Generated by Django 4.2.23 on 2025-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0008_procesosguardados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='onedrive_item_id',
            field=models.CharField(blank=True, help_text='ID único del item en OneDrive para sincronización', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='onedrive_url',
            field=models.CharField(blank=True, help_text='URL del archivo en OneDrive (ej: /drive/items/ID)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local (Servidor)'), ('onedrive', 'OneDrive')], default='local', help_text='Tipo de almacenamiento: local o en la nube', max_length=20),
        ),
        migrations.AddField(
            model_name='datasource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
